package org.jeecg.modules.teaching.enums;

public enum DepartDayLogType {
    UNIT_OPEN_COUNT,
    COURSE_WORK_ASSIGN_COUNT,
    ADDITIONAL_WORK_ASSIGN_COUNT,
    COURSE_WORK_SUBMIT_COUNT,
    ADDITIONAL_WORK_SUBMIT_COUNT,
    COURSE_WORK_CORRECT_COUNT,
    ADDITIONAL_WORK_CORRECT_COUNT;
}
